#!/usr/bin/env/ bash
# Generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root -p "$1" --all-databases > all_databases.sql
tar -czf "$(date +"%d-%m-%Y")".tar.gz all_databases.sql
