#!/usr/bin/env bash
# Displays the content of the file /etc/passwd.
# The script should only display:
# username
# user id
# Home directory path for the user

file=/etc/passwd
while read line
do
	echo "$line" | cut -d ':' -f1,3,6
done <$file
