#!/usr/bin/env bash
# Nginx runs as nginx but short and sweet ?
pkill -f apache2
sed -i s/80/8080/g /etc/nginx/sites-available/default
chmod 666 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
